// lib/consistency-route.mjs
// POST /api/map/consistency — measure ONE candidate under several
// caller-supplied text variants on the same frozen frame, and report whether
// the geometric reading agrees across them.
//
// Methodology transplant (consistency): FixMatch (Sohn, Berthelot, Li,
// Zhang, Carlini, Cubuk, Kurakin, Zhang, Raffel, NeurIPS 2020,
// arXiv:2001.07685) and UDA (arXiv:1904.12848) trust a pseudo-label only when
// the model's reading is stable between a weak and a strong augmentation of
// the same input. The wayfinder has no labels and no trainable model, so the
// only honest transplant is the diagnostic half: a rung whose sign of
// isolated_delta flips between two innocuous phrasings of the same edit is a
// perturbation-sensitive reading, and the caller should know that BEFORE
// spending an independent task check on it.
//
// What this IS: a stability diagnostic on the geometric reading of one edit.
// What this is NOT: a gate. Agreement does not authorize keeping; disagreement
// does not authorize reverting. The API never generates augmentations (there
// is no canonical text augmentation, and a server-made one would be tuned to
// the instrument). Variants are supplied by the caller and echoed by hash.
//
// Boundaries (asserted by test-axis-consistency.mjs):
//   - Every variant is measured by the real mapPreviewHandler, so the frozen
//     frame, exact-source-hash checks, anchor verification and no-persist
//     discipline are inherited. NO D1 write, NO Vectorize write.
//   - All shape checks (labels unique, 1..3 variants, texts nonempty, target
//     shape) run BEFORE any AI/KV work.
//   - Output is per-measurement facts plus set-level agreement booleans and
//     counts. No aggregate score, no averaging of deltas into a "consensus".

import { ApiError } from "./http.mjs";
import { MAX_ITEMS } from "./limits.mjs";
import { sha256Hex } from "./chunking.mjs";
import { mapPreviewHandler } from "./preview-route.mjs";

export const VERSION = "consistency";
export const MIN_VARIANTS = 1;
export const MAX_VARIANTS = 3;
export const MAX_LABEL = 40;
const INHERITED_ONLY = ["frame", "d", "K", "T", "seed", "steps", "threshold", "ideal", "preprocessing_id", "vectors", "persist", "labels"];
const REJECTED_KEYS = ["augment", "augmentation", "generate_variants", "strength", "gate", "threshold_confidence"];

export const SCOPE = "Stability diagnostic of one candidate edit under caller-supplied text variants on the same frozen frame. Agreement of the isolated-delta sign across variants means the geometric reading is not sensitive to those particular phrasings; disagreement means it is. Neither outcome authorizes keeping, reverting or deleting; the independent task check still governs. No variant is generated by the API and no consensus delta is computed.";

function ledgerDelta(l) {
  if (!l) return null;
  if (l.measurement && Number.isFinite(l.measurement.actual_delta)) return l.measurement.actual_delta;
  if (l.ledger && Number.isFinite(l.ledger.actual_delta)) return l.ledger.actual_delta;
  return Number.isFinite(l.actual_delta) ? l.actual_delta : null;
}
const sign = (x) => (x === null || !Number.isFinite(x)) ? "none" : x < 0 ? "negative" : x > 0 ? "positive" : "zero";

function validateRequest(body) {
  if (!body || typeof body !== "object" || Array.isArray(body)) throw new ApiError(422, "request must be an object");
  if (!Number.isSafeInteger(body.baseline_id) || body.baseline_id < 1) throw new ApiError(422, "baseline_id must be a positive integer");
  const { texts, names, target } = body;
  if (!Array.isArray(texts) || texts.length < 10 || texts.length > MAX_ITEMS) throw new ApiError(422, `texts must be the FULL resulting corpus (with the primary candidate) as 10..${MAX_ITEMS} items`);
  texts.forEach((t, i) => { if (typeof t !== "string" || !t.trim()) throw new ApiError(422, `texts[${i}] must be a nonempty string`); });
  if (!Array.isArray(names) || names.length !== texts.length) throw new ApiError(422, "names must contain one literal path per text");
  names.forEach((n, i) => { if (typeof n !== "string" || !n.length) throw new ApiError(422, `names[${i}] must be a nonempty string`); });
  if (new Set(names).size !== names.length) throw new ApiError(422, "names must be unique stable paths");
  if (!target || typeof target !== "object" || Array.isArray(target)) throw new ApiError(422, "target must be an object");
  if (target.action !== "add" && target.action !== "change") throw new ApiError(422, "target.action must be 'add' or 'change'");
  if (typeof target.name !== "string" || !target.name.length) throw new ApiError(422, "target.name must be a nonempty string");
  const ti = names.indexOf(target.name);
  if (ti < 0) throw new ApiError(422, "target.name must be present in names (the primary candidate text is texts[names.indexOf(target.name)])");
  const variants = body.variants;
  if (!Array.isArray(variants) || variants.length < MIN_VARIANTS || variants.length > MAX_VARIANTS) throw new ApiError(422, `variants must contain ${MIN_VARIANTS}..${MAX_VARIANTS} entries {label, text}`);
  const labels = new Set(["primary"]);
  variants.forEach((v, i) => {
    if (!v || typeof v !== "object" || Array.isArray(v)) throw new ApiError(422, `variants[${i}] must be an object {label, text}`);
    if (typeof v.label !== "string" || !v.label.trim() || v.label.length > MAX_LABEL) throw new ApiError(422, `variants[${i}].label must be a nonempty string of at most ${MAX_LABEL} chars`);
    if (labels.has(v.label)) throw new ApiError(422, `variants[${i}].label duplicates another label ('primary' is reserved)`);
    labels.add(v.label);
    if (typeof v.text !== "string" || !v.text.trim()) throw new ApiError(422, `variants[${i}].text must be a nonempty string`);
  });
  for (const k of REJECTED_KEYS) if (body[k] !== undefined) throw new ApiError(422, `${k} is not accepted: the API never generates variants and never gates on agreement`, { rejected_keys: REJECTED_KEYS });
  for (const k of INHERITED_ONLY) if (body[k] !== undefined) throw new ApiError(409, `consistency inherits the baseline's frozen frame and settings; remove ${k} from the request`, { inherited_only: INHERITED_ONLY });
  let predicted_delta = null;
  if (body.predicted_delta != null) { if (typeof body.predicted_delta !== "number" || !Number.isFinite(body.predicted_delta)) throw new ApiError(422, "predicted_delta must be a finite number"); predicted_delta = body.predicted_delta; }
  return { texts, names, target: { action: target.action, name: target.name }, targetIndex: ti, variants: variants.map((v) => ({ label: v.label, text: v.text })), predicted_delta };
}

function measurementOf(label, r, targetName, textSha) {
  const per = r.comparison && Array.isArray(r.comparison.per_name) ? r.comparison.per_name.find((x) => x.name === targetName) : null;
  const iso = r.comparison && Number.isFinite(r.comparison.isolated_delta) ? r.comparison.isolated_delta : ledgerDelta(r.math_ledger);
  return {
    label, sha256: textSha, noop: !!(r.target && r.target.noop),
    isolated_delta: iso, isolated_sign: sign(iso), ledger_actual_delta: ledgerDelta(r.math_ledger),
    bits_changed: per ? per.bits_changed : (r.comparison ? r.comparison.bits_changed_total ?? null : null),
    displacement_geodesic: per ? per.displacement_geodesic : null,
    quantization_silent: per ? !!per.quantization_silent : null,
    occupied_sectors_delta: r.comparison && Number.isFinite(r.comparison.occupied_sectors_delta) ? r.comparison.occupied_sectors_delta : null,
    unchanged_anchor_count: r.unchanged_anchor_count, frame_id: r.map && r.map.frame_id, instrument_id: r.map && r.map.instrument_id,
    comparison_comparable: r.comparison ? r.comparison.comparable !== false : false,
  };
}

/** ctx: { env, PM, embedDocuments, loadStoredMap, previewHandler? } */
export async function mapConsistencyHandler(body, ctx) {
  const { env, PM, embedDocuments, loadStoredMap } = ctx;
  const preview = ctx.previewHandler || mapPreviewHandler;
  const v = validateRequest(body);
  const pctx = { env, PM, embedDocuments, loadStoredMap };
  const measurements = [];
  const primarySha = await sha256Hex(v.texts[v.targetIndex]);
  const primary = await preview({ baseline_id: body.baseline_id, texts: v.texts, names: v.names, target: v.target, predicted_delta: v.predicted_delta ?? undefined }, pctx);
  measurements.push(measurementOf("primary", primary, v.target.name, primarySha));
  for (const variant of v.variants) {
    const texts = v.texts.slice(); texts[v.targetIndex] = variant.text;
    const sha = await sha256Hex(variant.text);
    const r = await preview({ baseline_id: body.baseline_id, texts, names: v.names, target: v.target, predicted_delta: v.predicted_delta ?? undefined }, pctx);
    measurements.push(measurementOf(variant.label, r, v.target.name, sha));
  }
  const signs = measurements.map((m) => m.isolated_sign);
  const signSet = [...new Set(signs)];
  const deltas = measurements.map((m) => m.isolated_delta).filter((x) => Number.isFinite(x));
  const distinctTexts = new Set(measurements.map((m) => m.sha256)).size;
  const predSign = sign(v.predicted_delta);
  const consistency = {
    n_measurements: measurements.length,
    n_distinct_texts: distinctTexts,
    signs, sign_set: signSet,
    all_same_sign: signSet.length === 1 && signSet[0] !== "none",
    all_comparable: measurements.every((m) => m.comparison_comparable),
    delta_min: deltas.length ? Math.min(...deltas) : null, delta_max: deltas.length ? Math.max(...deltas) : null,
    delta_spread: deltas.length ? Math.max(...deltas) - Math.min(...deltas) : null,
    bits_moved_count: measurements.filter((m) => m.bits_changed > 0).length,
    quantization_silent_count: measurements.filter((m) => m.quantization_silent).length,
    noop_count: measurements.filter((m) => m.noop).length,
    predicted_sign: predSign,
    sign_exact_count: predSign === "none" ? null : measurements.filter((m) => m.isolated_sign === predSign).length,
    reading: signSet.length === 1 && signSet[0] !== "none"
      ? "the isolated-delta sign is stable across the supplied variants on this frame; this is a stability statement about the reading, not a quality statement about the edit"
      : "the isolated-delta sign differs across the supplied variants; the geometric reading of this edit is perturbation-sensitive and should be treated as undetermined for planning purposes (it is not evidence against the edit)",
    note: distinctTexts < measurements.length ? "some variants are byte-identical to each other or to the primary; identical texts necessarily agree and add no evidence" : null,
  };
  return {
    consistency_check: true, persisted: false, version: VERSION, baseline_id: body.baseline_id,
    target: v.target, measurements, consistency,
    comparison_note: v.target.action === "add" ? "ADD comparisons are name-set incomparable in PM.compareMaps; isolated_delta comes from the exact ledger and per-name displacement is unavailable" : "per-name comparison on the inherited frozen frame",
    side_effects: { map_storage: false, repository: false, vectorize: false, embedding_cache: true },
    side_effects_note: "each measurement runs through the existing preview path; only the content-hash embedding cache may gain entries",
    scope: SCOPE,
    task_verdict: "not-tested",
    task_verdict_note: "agreement across variants is not a substitute for the independent task check; it only tells you whether that check would be spent on a stable geometric reading",
  };
}
