// test/browser-test.mjs — headless Chrome verification of the local copies.
//
// Uses the pre-installed chrome-headless-shell via puppeteer-core. It never
// downloads or installs a browser.
//
// TEST DOUBLES (explicit, so nothing here is mistaken for a live check):
//   * the HTTP server is test/server.mjs, a stdlib fixture server;
//   * /api/map and /api/map/preview return canned responses from
//     test/fixtures.json (maps + ledgers generated by the REAL pointmap.js);
//   * navigator.clipboard is stubbed per-page so copies are observable.
// The only non-double is /AGENT.md, which is served byte-for-byte from the
// local file so the guide comparison is genuine.
//
// The final live check against the deployed API is the parent's job, not this
// script's. Nothing here proves the production worker works.
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { createRequire } from "node:module";
import { startServer } from "./server.mjs";

const require = createRequire(import.meta.url);
const puppeteer = require("puppeteer-core");

const here = path.dirname(fileURLToPath(import.meta.url));
const root = path.join(here, "..");
const shots = path.join(root, "shots");
fs.mkdirSync(shots,{recursive:true});
const CHROME = process.argv[2] || "/usr/local/bin/chrome-headless-shell";

const AGENT_MD = fs.readFileSync(path.join(root, "AGENT.md"), "utf8");
const AGENT_MD_BYTES = fs.readFileSync(path.join(root, "AGENT.md"));
const fx = JSON.parse(fs.readFileSync(path.join(here, "fixtures.json"), "utf8"));

const results = [];
let failed = 0;
function check(name, ok, detail) {
  results.push({ name, ok: !!ok, detail: detail === undefined ? "" : String(detail) });
  if (!ok) failed++;
  console.log(`${ok ? "PASS" : "FAIL"}  ${name}${detail ? "  :: " + detail : ""}`);
}

// Clipboard stub. mode "ok" resolves; "deny" removes the async API entirely so
// the execCommand fallback runs; execOk decides what execCommand reports.
const clipboardStub = (mode, execOk) => `
  window.__clip = [];
  window.__execCalls = 0;
  document.execCommand = function () { window.__execCalls++; return ${execOk ? "true" : "false"}; };
  ${mode === "ok"
    ? `Object.defineProperty(navigator, "clipboard", { configurable: true, value: { writeText: function (t) { window.__clip.push(t); return Promise.resolve(); } } });`
    : `Object.defineProperty(navigator, "clipboard", { configurable: true, value: undefined });`}
`;

const DESKTOP = { width: 1365, height: 900 };
const MOBILE = { width: 375, height: 720, isMobile: true, hasTouch: true };

async function clickSafe(page, sel) {
  await page.$eval(sel, (e) => e.scrollIntoView({ block: "center", inline: "center", behavior: "instant" }));
  await new Promise((r) => setTimeout(r, 800));
  await page.click(sel);
}

async function newPage(browser, viewport, initScript) {
  const page = await browser.newPage();
  await page.setViewport(viewport);
  const errors = [];
  page.on("pageerror", (e) => errors.push(String(e && e.message)));
  page.on("console", (m) => {
    if (m.type() !== "error") return;
    const t = m.text();
    // Third-party asset loads (fonts, the ElevenLabs widget) cannot resolve in
    // this offline sandbox. That is an environment artifact, not a defect in
    // the files under test, so it is excluded from the JS-error assertion.
    if (/Failed to load resource|ERR_CERT|ERR_NAME_NOT_RESOLVED|ERR_INTERNET_DISCONNECTED|ERR_CONNECTION/.test(t)) return;
    errors.push("console: " + t);
  });
  if (initScript) await page.evaluateOnNewDocument(initScript);
  page.__errors = errors;
  return page;
}

async function run() {
  const { server, state, port } = await startServer(0);
  const BASE = `http://127.0.0.1:${port}`;
  const browser = await puppeteer.launch({
    executablePath: CHROME,
    headless: true,
    args: ["--no-sandbox", "--disable-dev-shm-usage"],
  });

  try {
    // =====================================================================
    // A. HOMEPAGE — copy agent guide
    // =====================================================================
    for (const [label, viewport] of [["desktop", DESKTOP], ["mobile", MOBILE]]) {
      const page = await newPage(browser, viewport, clipboardStub("ok", true));
      await page.goto(BASE + "/", { waitUntil: "domcontentloaded" });
      await page.waitForSelector("#copyagent");

      const label0 = await page.$eval("#copyagent-label", (e) => e.textContent.trim());
      check(`[${label}] button is usable immediately (no "waking the map", not gated on the iframe)`,
        label0 === "Copy agent guide", `label="${label0}"`);

      const box = await page.$eval("#copyagent", (e) => { const r = e.getBoundingClientRect(); return { w: r.width, h: r.height, disabled: e.disabled === true }; });
      check(`[${label}] button is not disabled`, !box.disabled);
      check(`[${label}] button has a real layout box (reachable, not display:none)`, box.w > 0 && box.h > 0, `${box.w}x${box.h}`);
      if (label === "mobile") {
        const frameShown = await page.$eval(".sos-frame", (e) => getComputedStyle(e).display !== "none");
        check("[mobile] the heavy iframe stays hidden while the button is reachable", !frameShown);
      }

      await clickSafe(page, "#copyagent");
      await page.waitForFunction("window.__clip.length > 0", { timeout: 8000 });
      const copied = await page.evaluate(() => window.__clip[0]);

      check(`[${label}] copied text is byte-exact /AGENT.md`, copied === AGENT_MD,
        `copied ${Buffer.byteLength(copied, "utf8")} bytes vs file ${AGENT_MD_BYTES.length} bytes`);
      check(`[${label}] copied text is NOT the old hardcoded recipe`,
        !copied.includes("Ingest a corpus:") && copied.startsWith("# SOS AGENT"));
      const okVisible = await page.$eval("#copyagent-ok", (e) => getComputedStyle(e).display !== "none");
      check(`[${label}] success indicator shown after a real copy`, okVisible);

      await page.screenshot({ path: path.join(shots, `home-copy-${label}.png`) });
      check(`[${label}] homepage has no page errors`, page.__errors.length === 0, page.__errors.join(" | "));
      await page.close();
    }

    // --- fetch failure must be visible, never a false "copied" ---
    state.agentMdMode = "http500";   // in-process: node fetch to loopback is proxy-blocked here
    {
      const page = await newPage(browser, DESKTOP, clipboardStub("ok", true));
      await page.goto(BASE + "/", { waitUntil: "domcontentloaded" });
      await clickSafe(page, "#copyagent");
      await page.waitForFunction(
        "document.getElementById('copyagent-err') && getComputedStyle(document.getElementById('copyagent-err')).display !== 'none'",
        { timeout: 8000 });
      const err = await page.$eval("#copyagent-err", (e) => e.textContent);
      const href = await page.$eval("#copyagent-err a", (e) => e.getAttribute("href"));
      const clip = await page.evaluate(() => window.__clip.length);
      const okShown = await page.$eval("#copyagent-ok", (e) => getComputedStyle(e).display !== "none");
      check("fetch failure surfaces a visible error", /couldn't copy the guide/.test(err), err.slice(0, 90));
      check("fetch failure offers the /AGENT.md link", href === "/AGENT.md", href);
      check("fetch failure copies NOTHING", clip === 0);
      check("fetch failure never claims 'copied'", !okShown);
      await page.screenshot({ path: path.join(shots, "home-copy-fetch-error.png") });
      await page.close();
    }

    // --- empty guide is also a failure, not a silent empty copy ---
    state.agentMdMode = "empty";
    {
      const page = await newPage(browser, DESKTOP, clipboardStub("ok", true));
      await page.goto(BASE + "/", { waitUntil: "domcontentloaded" });
      await clickSafe(page, "#copyagent");
      await page.waitForFunction(
        "getComputedStyle(document.getElementById('copyagent-err')).display !== 'none'", { timeout: 8000 });
      const clip = await page.evaluate(() => window.__clip.length);
      check("empty guide is rejected, nothing copied", clip === 0);
      await page.close();
    }

    // --- execCommand fallback: only a `true` return counts as copied ---
    state.agentMdMode = "ok";
    {
      const page = await newPage(browser, DESKTOP, clipboardStub("deny", false));
      await page.goto(BASE + "/", { waitUntil: "domcontentloaded" });
      await clickSafe(page, "#copyagent");
      await page.waitForFunction("window.__execCalls > 0", { timeout: 8000 });
      const okShown = await page.$eval("#copyagent-ok", (e) => getComputedStyle(e).display !== "none");
      const errShown = await page.$eval("#copyagent-err", (e) => getComputedStyle(e).display !== "none");
      check("execCommand returning false does NOT claim 'copied'", !okShown);
      check("execCommand returning false shows the manual-copy error", errShown);
      await page.close();
    }
    {
      const page = await newPage(browser, DESKTOP, clipboardStub("deny", true));
      await page.goto(BASE + "/", { waitUntil: "domcontentloaded" });
      await clickSafe(page, "#copyagent");
      await page.waitForFunction(
        "getComputedStyle(document.getElementById('copyagent-ok')).display !== 'none'", { timeout: 8000 });
      check("execCommand returning true DOES claim 'copied'", true);
      await page.close();
    }

    // =====================================================================
    // B. MAP UI — candidate preview
    // =====================================================================
    const page = await newPage(browser, DESKTOP, clipboardStub("ok", true));
    await page.goto(BASE + "/map/", { waitUntil: "domcontentloaded" });
    await page.waitForSelector("#preview");
    await page.waitForFunction("document.getElementById('status').textContent.startsWith('done')", { timeout: 90000 });

    check("no frozen baseline on load", /no frozen baseline yet/.test(
      await page.$eval("#candbaseline", (e) => e.textContent)));

    // preview without a baseline must refuse locally, sending nothing
    const before = state.requests.filter((r) => r.path === "/api/map/preview").length;
    await page.type("#candname", "skills/new-candidate/SKILL.md");
    await page.type("#candtext", "draft body for the candidate document");
    await clickSafe(page, "#preview");
    await page.waitForSelector("#canderrors", { visible: true });
    check("preview without a frozen baseline is refused client-side",
      /No frozen text baseline/.test(await page.$eval("#canderrors", (e) => e.textContent)));
    check("refusal sends no request",
      state.requests.filter((r) => r.path === "/api/map/preview").length === before);

    // run a texts map so a real corpus is submitted and saved
    await page.select("#src", "texts");
    await page.evaluate((n) => {
      const ta = document.getElementById("input");
      ta.value = Array.from({ length: n }, (_, i) => `fixture corpus line ${i} with enough words to look like a document`).join("\n");
    }, fx.baseline_names.length);
    await clickSafe(page, "#run");
    await page.waitForFunction("document.getElementById('meta').textContent.includes('51')", { timeout: 60000 });
    check("text map saved with a server id", true, "map id 51");

    const mapPosts = state.requests.filter((r) => r.path === "/api/map" && r.method === "POST");
    check("submitted names are the literal line ordinals",
      JSON.stringify(mapPosts[0].body.names) === JSON.stringify(fx.baseline_names));

    await clickSafe(page, "#useBaseline");
    const banner = await page.$eval("#candbaseline", (e) => e.textContent);
    check("'use as baseline' freezes the submitted corpus",
      /frozen baseline: map id 51/.test(banner) && /14 verified documents/.test(banner), banner.slice(0, 80));

    // mutating the controls afterwards must NOT change the frozen snapshot
    await page.evaluate(() => { document.getElementById("input").value = "totally different corpus"; });
    const stillFrozen = await page.$eval("#candbaseline", (e) => e.textContent);
    check("frozen snapshot survives later control edits", /14 verified documents/.test(stillFrozen));

    // ---- ADD preview ----
    await page.evaluate(() => {
      document.getElementById("candname").value = "";
      document.getElementById("candtext").value = "";
      document.getElementById("canddelta").value = "";
    });
    await page.select("#candaction", "add");
    await page.type("#candname", fx.add_name);
    await page.type("#candtext", "a brand new candidate document body");
    await clickSafe(page, "#preview");
    await page.waitForSelector("#previewout", { visible: true });

    const addReq = state.requests.filter((r) => r.path === "/api/map/preview").pop();
    check("ADD sends the FULL resulting corpus", addReq.body.texts.length === 15 && addReq.body.names.length === 15,
      `${addReq.body.texts.length} items`);
    check("ADD sends target {action,name}",
      addReq.body.target.action === "add" && addReq.body.target.name === fx.add_name);
    check("no instrument fields are sent (d/K/T/seed/frame/labels)",
      ["d", "K", "T", "seed", "frame", "steps", "threshold", "labels", "persist", "vectors"]
        .every((k) => addReq.body[k] === undefined), Object.keys(addReq.body).join(","));
    check("blank predicted delta is OMITTED, not coerced to 0",
      !("predicted_delta" in addReq.body), JSON.stringify(Object.keys(addReq.body)));

    const out = await page.$eval("#previewout", (e) => e.textContent);
    check("ADD ledger renders as ADD with its neutrality stated",
      /ADD/.test(out) && /neutral by construction/.test(out));
    check("ADD ledger shows the exact isolated-count delta", /isolated-count delta \(identity\)/.test(out));
    check("ADD ledger names the touched previous isolate", out.includes("line:0"));
    check("ratio is withheld with its reason when no prediction was given",
      /withheld - no predicted_delta supplied/.test(out), (out.match(/withheld[^.]*/) || [""])[0]);
    check("margins declare the missing roundoff bound",
      /no roundoff bound was supplied/.test(out) && /needs-roundoff-bound/.test(out));
    check("margins are stated as signed score units, not probability",
      /score units of this frozen axis/.test(out) && /not numerical proofs or probabilities/.test(out));
    check("margins are read from math_diagnostics.per_input",
      /map.math_diagnostics.per_input/.test(out) && !/FIXTURE: top-level map_diagnostics/.test(out));
    check("persisted:false and side effects are shown",
      /persisted/.test(out) && /map_storage=false/.test(out) && /repository=false/.test(out) &&
      /vectorize=false/.test(out) && /embedding_cache=true/.test(out));
    check("task_verdict is surfaced as not-tested", /not-tested/.test(out));
    check("unchanged anchors are reported", /unchanged anchors/.test(out));

    // preview must NOT disturb the saved baseline
    const afterAdd = await page.evaluate(() => ({
      baselineField: document.getElementById("baseline").value,
      meta: document.getElementById("meta").textContent,
      cand: document.getElementById("candbaseline").textContent,
    }));
    check("preview does not overwrite the saved baseline id", afterAdd.baselineField === "51");
    check("preview does not replace the rendered saved map", afterAdd.meta.includes("51"));
    check("preview does not mutate the frozen corpus", /frozen baseline: map id 51/.test(afterAdd.cand));
    check("preview never persisted anything",
      state.requests.filter((r) => r.path === "/api/map" && r.method === "POST").length === 1);
    await page.screenshot({ path: path.join(shots, "map-preview-add.png"), fullPage: true });

    // ---- CHANGE preview (unchanged geometry) ----
    await page.select("#candaction", "change");
    await page.evaluate((n) => {
      document.getElementById("candname").value = n;
      document.getElementById("candtext").value = "edited body that does not move the point";
      document.getElementById("canddelta").value = "-2";
    }, fx.change_name);
    await clickSafe(page, "#preview");
    await page.waitForFunction("document.getElementById('previewout').textContent.includes('CHANGE')", { timeout: 15000 });

    const chgReq = state.requests.filter((r) => r.path === "/api/map/preview").pop();
    check("CHANGE keeps the same name set", chgReq.body.names.length === 14);
    check("CHANGE sends a supplied predicted_delta verbatim", chgReq.body.predicted_delta === -2);

    const out2 = await page.$eval("#previewout", (e) => e.textContent);
    check("CHANGE with no movement renders as 'unchanged', distinct from ADD",
      /CHANGE - unchanged/.test(out2) && /no point moved on the frozen frame/.test(out2));
    check("unchanged CHANGE shows delta 0 and no touched neighbours",
      /isolated-count delta \(identity\)\s*0/.test(out2.replace(/\s+/g, " ")) || /delta \(identity\)/.test(out2));
    await page.screenshot({ path: path.join(shots, "map-preview-change.png"), fullPage: true });

    // ---- guards ----
    await page.evaluate(() => { document.getElementById("baseline").value = "999"; });
    await clickSafe(page, "#preview");
    await page.waitForSelector("#canderrors", { visible: true });
    check("a manual baseline id that disagrees with the frozen corpus is refused",
      /baseline id field says 999/i.test(await page.$eval("#canderrors", (e) => e.textContent)));
    await page.evaluate(() => { document.getElementById("baseline").value = "51"; });

    await page.evaluate(() => { document.getElementById("canddelta").value = "abc"; });
    await clickSafe(page, "#preview");
    check("a non-numeric predicted delta is refused, never coerced",
      /must be a finite number/.test(await page.$eval("#canderrors", (e) => e.textContent)));
    await page.evaluate(() => { document.getElementById("canddelta").value = ""; });

    await page.select("#candaction", "add");
    await page.evaluate((n) => { document.getElementById("candname").value = n; }, fx.change_name);
    await clickSafe(page, "#preview");
    check("ADD onto an existing name is refused",
      /is present at index/.test(await page.$eval("#canderrors", (e) => e.textContent)));

    await page.select("#candaction", "change");
    await page.evaluate(() => { document.getElementById("candname").value = "nope/not/here.md"; });
    await clickSafe(page, "#preview");
    check("CHANGE of an unknown name is refused",
      /not in the frozen corpus/.test(await page.$eval("#canderrors", (e) => e.textContent)));

    // ---- escaping ----
    const XSS = '<img src=x onerror="window.__pwned=1">';
    await page.select("#candaction", "add");
    await page.evaluate((x) => {
      document.getElementById("candname").value = x;
      document.getElementById("candtext").value = "body";
    }, XSS);
    await page.evaluate(() => { document.getElementById("previewout").innerHTML = ""; });
    await clickSafe(page, "#preview");
    // Wait for THIS render, not the previous one: the panel was already visible.
    await page.waitForFunction("document.getElementById('previewout').textContent.includes('onerror')", { timeout: 15000 });
    const pwned = await page.evaluate(() => window.__pwned === 1);
    const imgs = await page.evaluate(() => document.querySelectorAll('#previewout img, #canderrors img').length);
    const shown = await page.evaluate(() => document.getElementById("previewout").textContent + document.getElementById("canderrors").textContent);
    check("a name containing markup does not execute", !pwned && imgs === 0);
    check("the markup is rendered as visible text", shown.includes("onerror"));

    check("map UI has no page errors", page.__errors.length === 0, page.__errors.join(" | "));

    // mobile pass over the candidate editor
    await page.setViewport(MOBILE);
    await page.screenshot({ path: path.join(shots, "map-preview-mobile.png"), fullPage: true });
    const reachable = await page.evaluate(() => {
      const b = document.getElementById("preview").getBoundingClientRect();
      return b.width > 0 && b.height > 0;
    });
    check("[mobile] candidate preview control is reachable", reachable);
    await page.close();
  } finally {
    await browser.close();
    server.close();
  }

  const receipt = {
    generated_at: new Date().toISOString(),
    runner: "puppeteer-core + " + CHROME + " (pre-installed; nothing downloaded)",
    test_doubles: [
      "test/server.mjs — local stdlib fixture server, not the production worker",
      "/api/map and /api/map/preview — canned responses from test/fixtures.json",
      "test/fixtures.json — maps and math ledgers generated by the REAL pointmap.js core",
      "navigator.clipboard and document.execCommand — stubbed per page so copies are observable",
    ],
    not_a_double: ["/AGENT.md is served byte-for-byte from the local AGENT.md file"],
    not_covered: "the deployed API at steady-orbit.systems-a.workers.dev was never contacted; the live check is the parent's job",
    total: results.length,
    passed: results.length - failed,
    failed,
    results,
  };
  fs.writeFileSync(path.join(here, "receipt.json"), JSON.stringify(receipt, null, 2));
  console.log(`\n${receipt.passed}/${receipt.total} passed, ${failed} failed`);
  process.exit(failed ? 1 : 0);
}

run().catch((e) => { console.error("HARNESS ERROR:", e); process.exit(2); });
