// test/server.mjs — LOCAL TEST DOUBLE. Serves the local copies of home.html /
// index.html / app.js / pointmap.js / AGENT.md and answers /api/map and
// /api/map/preview from test/fixtures.json.
//
// This is NOT the production worker. Every /api/* response here is a canned
// fixture generated by test/make-fixtures.mjs from the real pointmap.js core.
// It exists so the browser test can exercise the UI deterministically and
// offline. The final live check against the real API is the parent's job.
import http from "node:http";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const here = path.dirname(fileURLToPath(import.meta.url));
const root = path.join(here, "..");
const fx = JSON.parse(fs.readFileSync(path.join(here, "fixtures.json"), "utf8"));

export function startServer(port = 0) {
  const state = { agentMdMode: "ok", requests: [] };

  const file = (rel, type) => ({ body: fs.readFileSync(path.join(root, rel)), type });
  const send = (res, status, type, body) => {
    res.writeHead(status, { "Content-Type": type, "Cache-Control": "no-store" });
    res.end(body);
  };

  const server = http.createServer((req, res) => {
    const url = new URL(req.url, "http://127.0.0.1");
    const p = url.pathname;
    state.requests.push({ method: req.method, path: p });

    // ---- test control plane (never part of the product) ----
    if (p === "/__test/agentmd") { state.agentMdMode = url.searchParams.get("mode") || "ok"; return send(res, 200, "text/plain", "ok"); }
    if (p === "/__test/requests") return send(res, 200, "application/json", JSON.stringify(state.requests));

    if (p === "/" || p === "/index.html") { const f = file("home.html", "text/html; charset=utf-8"); return send(res, 200, f.type, f.body); }

    if (p === "/AGENT.md") {
      if (state.agentMdMode === "http500") return send(res, 500, "text/plain; charset=utf-8", "upstream exploded");
      if (state.agentMdMode === "empty") return send(res, 200, "text/markdown; charset=utf-8", "   \n  ");
      const f = file("AGENT.md", "text/markdown; charset=utf-8");
      return send(res, 200, f.type, f.body);            // byte-for-byte, no transform
    }

    if (p === "/map" || p === "/map/") { const f = file("index.html", "text/html; charset=utf-8"); return send(res, 200, f.type, f.body); }
    if (p === "/map/app.js") { const f = file("app.js", "text/javascript; charset=utf-8"); return send(res, 200, f.type, f.body); }
    if (p === "/map/pointmap.js") { const f = file("pointmap.js", "text/javascript; charset=utf-8"); return send(res, 200, f.type, f.body); }

    if (req.method === "POST" && (p === "/api/map" || p === "/api/map/preview")) {
      let raw = "";
      req.on("data", (c) => { raw += c; });
      req.on("end", () => {
        let body = null;
        try { body = JSON.parse(raw); } catch { return send(res, 400, "application/json", JSON.stringify({ error: "bad json" })); }
        state.requests[state.requests.length - 1].body = body;

        if (p === "/api/map") return send(res, 200, "application/json", JSON.stringify(fx.map_response));

        // /api/map/preview — mirror the real route's own guards so the UI is
        // tested against refusals it will actually meet in production.
        for (const k of ["frame", "d", "K", "T", "seed", "steps", "threshold", "labels", "vectors", "persist"]) {
          if (body[k] !== undefined) return send(res, 409, "application/json", JSON.stringify({ error: `preview inherits the baseline's frozen frame and settings; remove ${k} from the request` }));
        }
        if (!body.target || (body.target.action !== "add" && body.target.action !== "change")) {
          return send(res, 422, "application/json", JSON.stringify({ error: "target.action must be 'add' or 'change'" }));
        }
        const chosen = body.target.action === "add" ? fx.preview_add : fx.preview_change_unchanged;
        const out = { ...chosen, target: { ...chosen.target, name: body.target.name, action: body.target.action } };
        return send(res, 200, "application/json", JSON.stringify(out));
      });
      return;
    }

    return send(res, 404, "text/plain", "not found");
  });

  return new Promise((resolve) => {
    server.listen(port, "127.0.0.1", () => resolve({ server, state, port: server.address().port }));
  });
}

if (process.argv[1] && process.argv[1].endsWith("server.mjs")) {
  startServer(8787).then(({ port }) => console.log("fixture server on http://127.0.0.1:" + port));
}
