"""verify_visco.py -- Python SOURCE OF RECORD for the jev-corpus viscoelastic
instrument surface (SPEC-VISCO sec.0-2; round-3 creep-recovery replay anchors).

Pure stdlib (json, math only; numpy FORBIDDEN). Four pure functions:

    persistence_stats   -- C1: did applied load flips survive independent re-grading?
    hysteresis_rollup   -- C2: prediction dissipation over a supersedes-closed ledger
    prony_fit           -- C3: deterministic Prony relaxation fit (grid + normal eqns)
    snapback_detect     -- C4: consecutive-inversion run detector with gate input

SIGN CONVENTIONS (this program's convention, AGENT.md sign gate):
  * dBc improvement = MORE NEGATIVE. A dBc of -16.9 is better (further from the
    null) than -11.1.
  * predicted_delta / realized_delta are passed in EXACTLY the sign convention
    they were recorded in, with no re-interpretation: realized_delta = +0.16
    means "dBc moved +0.16 in the recorded frame" (toward the null, i.e. worse).
    predicted_delta = +11.50 means "predicted 11.50 of improvement magnitude in
    the same recorded frame". These functions compare SIGNS, never polarity of
    the underlying dBc axis, so the convention travels unchanged to the JS port.
  * persistence deltas: delta = later_dbc - base_dbc (e.g. the replay's load leg
    moved +2.566: -14.318 - -16.884).

RATE-DEPENDENT RECOVERY R: explicitly out of scope v1. Under a deterministic
scorer the text-revert unload returns the matrix exactly (replay F3: R = 1.0,
60/60 identical axes), so R cannot separate edit classes; persistence under
independent re-grading is the discriminating measurement instead (replay F4).
Unlock condition: a rate-dependent / stochastic scorer owned by the caller.

Run `python3 verify_visco.py` to execute the fixture selftest; fixtures live at
fixtures/visco-fixtures.json next to this file (generated by generate_fixtures.py,
which runs THESE functions to freeze expected outputs -- fixtures are truth
because the source of record computed them).
"""

import json
import math

# ---------------------------------------------------------------------------
# helpers
# ---------------------------------------------------------------------------


def _sign(x):
    """Return -1, 0, or +1 (exact zero only)."""
    if x > 0:
        return 1
    if x < 0:
        return -1
    return 0


def _mean(xs):
    return sum(xs) / len(xs)


def _solve_normal(cols, ys):
    """Least squares via normal equations; Gaussian elimination w/ pivoting.

    cols: list of column vectors (each len n), ys: list of n observations.
    Returns coefficient list len(cols), or None when the normal matrix is
    singular (pivot below threshold) -- callers skip that candidate.
    """
    n = len(ys)
    m = len(cols)
    ata = [[sum(cols[a][i] * cols[b][i] for i in range(n)) for b in range(m)]
           for a in range(m)]
    aty = [sum(cols[a][i] * ys[i] for i in range(n)) for a in range(m)]
    scale = max(1.0, max((abs(v) for row in ata for v in row), default=1.0))
    aug = [row[:] + [aty[i]] for i, row in enumerate(ata)]
    for c in range(m):
        p = max(range(c, m), key=lambda r: abs(aug[r][c]))
        if abs(aug[p][c]) < 1e-12 * scale:
            return None
        aug[c], aug[p] = aug[p], aug[c]
        pv = aug[c][c]
        for r in range(c + 1, m):
            f = aug[r][c] / pv
            if f:
                for k in range(c, m + 1):
                    aug[r][k] -= f * aug[c][k]
    x = [0.0] * m
    for r in range(m - 1, -1, -1):
        s = aug[r][m] - sum(aug[r][k] * x[k] for k in range(r + 1, m))
        x[r] = s / aug[r][r]
    return x


def _fit_columns(cols, ys):
    """Solve for coefficients of `cols` against `ys`, clipping negative
    exponential-arm amplitudes to 0 and re-solving the reduced system until no
    negative arm remains. Column 0 (the constant / ke column) is never clipped.
    Returns full coefficient vector (0.0 for clipped arms) or None if singular."""
    active = list(range(len(cols)))
    while True:
        sub = [cols[i] for i in active]
        sol = _solve_normal(sub, ys)
        if sol is None:
            return None
        neg = [active[j] for j in range(1, len(active)) if sol[j] < 0.0]
        if not neg:
            out = [0.0] * len(cols)
            for j, i in enumerate(active):
                out[i] = sol[j]
            return out
        active = [i for i in active if i not in neg]
        if len(active) == 0:  # unreachable: constant column always active
            return None


def _combinations(items, k):
    """Hand-rolled k-combinations (no itertools import; json/math-only rule)."""
    n = len(items)
    if k > n:
        return
    idx = list(range(k))
    while True:
        yield [items[i] for i in idx]
        j = k - 1
        while j >= 0 and idx[j] == n - k + j:
            j -= 1
        if j < 0:
            return
        idx[j] += 1
        for l in range(j + 1, k):
            idx[l] = idx[l - 1] + 1


# ---------------------------------------------------------------------------
# C1 -- persistence
# ---------------------------------------------------------------------------


def persistence_stats(applied_cells, regraded_passes, base_dbc, loaded_dbc,
                      regraded_dbcs):
    """C1 persistence: did the load's bit flips survive independent re-grading?

    Contract
    --------
    applied_cells : list of (row, axis) 2-tuples (or 2-lists) the load leg
        flipped. Direction is fixed: base bit 0 -> loaded bit 1. Rows are
        looked up by str(row) so int row ids match JSON string dict keys.
    regraded_passes : list of {"pass_id": str, "bits_by_row": {row: [12 bits]}}
        -- one entry per INDEPENDENT grader pass over the LOADED text. A pass
        missing a row simply does not credit that row's cells (counts as not
        persisted in that pass).
    base_dbc, loaded_dbc : floats, dBc of the base and loaded matrices.
    regraded_dbcs : list of float, dBc of each regraded pass (parallel to
        regraded_passes; len must match or ValueError).

    Persistence rule: a flip PERSISTS in a pass when the re-graded row credits
    bit 1 at that (row, axis) (bit 1 where base was 0). A cell is persisted
    OVERALL when it persists in EVERY pass (strictest rule; each pass is an
    independent blind re-grade, so survival must hold in all of them).
    per_pass_fractions carries the per-pass view; with one pass the two agree
    (the replay's 9/9 case is single-pass).

    Level math: delta_load = loaded - base; delta_regraded_passes[i] =
    regraded_dbcs[i] - base (positive = moved toward the null in the recorded
    frame; see module docstring sign conventions).

    Scorer variance (replay F1, first-class output):
      inter_pass_offset_dbc = max pairwise |dbc_i - dbc_j| across the REGRADED
        passes only (0.0 with fewer than 2 passes; a caller wanting to include
        another pass level appends it to regraded_dbcs/regraded_passes).
      max_bit_disagreement = over every (row, axis) cell present in >= 2
        passes, the number of pairwise pass pairs whose credited bits differ;
        max across cells (0 if no cell is covered by 2+ passes).

    Edge cases: applied_count 0 -> persistence_fraction 0.0 (nothing was
    flipped, nothing to persist); no regraded passes -> persisted_count 0,
    per_pass_fractions [], offset 0.0. Zero deltas are preserved exactly.
    Raises ValueError on regraded_dbcs/regraded_passes length mismatch.
    """
    if len(regraded_dbcs) != len(regraded_passes):
        raise ValueError("regraded_dbcs length must match regraded_passes")
    applied = [(str(cell[0]), int(cell[1])) for cell in applied_cells]
    applied_count = len(applied)

    per_pass_persisted = []
    for p in regraded_passes:
        bits_by_row = p.get("bits_by_row", {})
        count = 0
        for row, axis in applied:
            bits = bits_by_row.get(row)
            if bits is not None and axis < len(bits) and bits[axis] == 1:
                count += 1
        per_pass_persisted.append(count)

    per_pass_fractions = [
        (c / applied_count) if applied_count else 0.0
        for c in per_pass_persisted
    ]
    # overall: persisted in every pass
    persisted_count = 0
    for i in range(applied_count):
        if all(per_pass_persisted[p] > i for p in range(len(regraded_passes))):
            persisted_count += 1
    persistence_fraction = (persisted_count / applied_count) if applied_count else 0.0

    # scorer variance: pairwise dbc spread across regraded passes
    offset = 0.0
    for i in range(len(regraded_dbcs)):
        for j in range(i + 1, len(regraded_dbcs)):
            offset = max(offset, abs(regraded_dbcs[i] - regraded_dbcs[j]))

    # max pairwise bit disagreement across passes, per cell
    present = {}  # (row, axis) -> {pass_index: bit}
    for pi, p in enumerate(regraded_passes):
        for row, bits in p.get("bits_by_row", {}).items():
            for axis, bit in enumerate(bits):
                present.setdefault((str(row), axis), {})[pi] = bit
    max_bit_disagreement = 0  # MAX over cells of pairwise pass disagreements
    for cell, by_pass in present.items():
        if len(by_pass) < 2:
            continue
        idxs = sorted(by_pass)
        cell_pairs = 0
        for a in range(len(idxs)):
            for b in range(a + 1, len(idxs)):
                if by_pass[idxs[a]] != by_pass[idxs[b]]:
                    cell_pairs += 1
        max_bit_disagreement = max(max_bit_disagreement, cell_pairs)

    return {
        "applied_count": applied_count,
        "persisted_count": persisted_count,
        "persistence_fraction": persistence_fraction,
        "per_pass_fractions": per_pass_fractions,
        "level": {
            "dbc_base": float(base_dbc),
            "dbc_loaded": float(loaded_dbc),
            "dbc_regraded_passes": [float(d) for d in regraded_dbcs],
            "delta_load": float(loaded_dbc) - float(base_dbc),
            "delta_regraded_passes": [float(d) - float(base_dbc)
                                      for d in regraded_dbcs],
        },
        "scorer_variance": {
            "inter_pass_offset_dbc": offset,
            "max_bit_disagreement": max_bit_disagreement,
        },
    }


# ---------------------------------------------------------------------------
# C2 -- hysteresis rollup
# ---------------------------------------------------------------------------


def hysteresis_rollup(rows):
    """C2 hysteresis: prediction dissipation over the outcomes ledger.

    Contract
    --------
    rows : ledger rows, each {"id" or "cycle", "predicted_delta",
    "realized_delta", "supersedes" (id-or-null)}. Ids may be ints (cycle
    numbers) or strings; `supersedes` references must match the id key exactly.

    A supersedes CHAIN is r_root <- ... <- r_active (each link: the later row
    supersedes the earlier one, replacing it in the active set). Every chain
    is closed into one LOOP, oldest row first: chain_ids, predicted[],
    realized[] in chain order (oldest -> active). Hysteresis area per SPEC
    sec.2.5 = sum |predicted_delta - realized_delta| over the WHOLE chain
    (superseded attempts dissipate prediction too); mean_abs = sum_abs /
    len(chain). A row with no supersedes (and not superseded) is its own
    singleton loop.

    Returns
    -------
    loops : [{chain_ids, predicted, realized, sum_abs, mean_abs}] ordered by
        first appearance of the active row in the input; leftover rows caught
        in a supersedes cycle (malformed input) are appended as singleton
        loops so every input row is accounted for exactly once.
    active_rows : count of rows no other row supersedes (loop terminals).
    total_sum_abs : sum of loop sum_abs (covers all input rows exactly once).
    total_mean_per_cycle : total_sum_abs / n_cycles.
    n_cycles : number of loops (= one final outcome per ledger cycle; a
        chain's superseded attempts roll up into that cycle).

    Edge cases: unknown supersedes id -> treated as a root (chain stops
    there). supersedes cycles (a<->b) -> rows become singleton loops so
    totals never silently drop rows. Empty ledger -> all zeros/empty lists.
    Recorded round-3 anchor: 10 singleton loops, total_sum_abs = 102.86,
    mean_per_cycle = 10.29.
    """
    by_id = {}
    order = []
    for r in rows:
        rid = r["id"] if "id" in r else r["cycle"]
        if rid in by_id:
            raise ValueError("duplicate ledger row id: %r" % (rid,))
        by_id[rid] = r
        order.append(rid)

    superseded = set()
    for r in rows:
        sup = r.get("supersedes")
        if sup is not None and sup in by_id:
            superseded.add(sup)

    active_ids = [rid for rid in order if rid not in superseded]
    covered = set()
    loops = []

    def abs_dev(row):
        return abs(float(row["predicted_delta"]) - float(row["realized_delta"]))

    for rid in active_ids:
        chain = []
        seen = set()
        cur = by_id[rid]
        while True:
            cid = cur["id"] if "id" in cur else cur["cycle"]
            if cid in seen:  # defensive: supersedes cycle -> stop walk
                break
            seen.add(cid)
            chain.append(cur)
            sup = cur.get("supersedes")
            if sup is None or sup not in by_id or sup in seen:
                break
            cur = by_id[sup]
        chain.reverse()  # oldest -> active
        covered.update(cur_id for cur_id in seen)
        s = sum(abs_dev(row) for row in chain)
        loops.append({
            "chain_ids": [row["id"] if "id" in row else row["cycle"]
                          for row in chain],
            "predicted": [float(row["predicted_delta"]) for row in chain],
            "realized": [float(row["realized_delta"]) for row in chain],
            "sum_abs": s,
            "mean_abs": s / len(chain),
        })

    # rows caught in supersedes cycles never appear in an active chain;
    # emit them as singletons so total_sum_abs covers every input row
    for rid in order:
        if rid not in covered:
            row = by_id[rid]
            s = abs_dev(row)
            loops.append({
                "chain_ids": [rid],
                "predicted": [float(row["predicted_delta"])],
                "realized": [float(row["realized_delta"])],
                "sum_abs": s,
                "mean_abs": s,
            })

    total = sum(loop["sum_abs"] for loop in loops)
    n_cycles = len(loops)
    return {
        "loops": loops,
        "active_rows": len(active_ids),
        "total_sum_abs": total,
        "total_mean_per_cycle": (total / n_cycles) if n_cycles else 0.0,
        "n_cycles": n_cycles,
    }


# ---------------------------------------------------------------------------
# C3 -- Prony relaxation fit
# ---------------------------------------------------------------------------

DEFAULT_TAU_GRID_POINTS = 60
DEFAULT_TAU_LOG_LO = -2.0   # 1e-2
DEFAULT_TAU_LOG_HI = 4.0    # 1e4


def default_tau_grid():
    """Log-spaced tau grid, 60 points over 1e-2 .. 1e4 inclusive."""
    lo, hi, n = DEFAULT_TAU_LOG_LO, DEFAULT_TAU_LOG_HI, DEFAULT_TAU_GRID_POINTS
    return [10 ** (lo + (hi - lo) * i / (n - 1)) for i in range(n)]


def prony_fit(series, arms=2, tau_grid=None):
    """C3 deterministic Prony relaxation fit: value(t) ~= ke + sum k_j exp(-t/tau_j).

    Contract
    --------
    series : [{"t": number, "value": number}] ordered by ascending t; t may be
        a cycle index (SPEC sec.2.2 fallback when the runs store has no usable
        time column). Must contain at least arms+1 points or ValueError.
    arms : number of exponential arms, 1..3 (SPEC sec.2.4 caps K at 3; the
        grid-search cost grows combinatorially beyond that).
    tau_grid : optional explicit candidate tau list; default is the log-spaced
        60-point grid over 1e-2..1e4 (default_tau_grid()).

    Method (deterministic, no iterative optimizer): for every combination of
    `arms` distinct grid taus, build design columns [1, exp(-t/tau_j)...] and
    solve amplitudes by LINEAR LEAST SQUARES via pure-Python normal equations
    (Gaussian elimination with partial pivoting; small K so this is exact
    enough and fast). Negative exponential amplitudes are CLIPPED to 0 and
    the reduced system re-solved (repeat until no negative arm remains; the
    constant term ke is never clipped). Pick the (taus, amplitudes) minimizing
    SSE. Duplicate taus within a combination are skipped (singular).

    Determinism: same inputs -> same output on any platform, any language.
    The JS port must reproduce the same grid, the same combination order
    (ascending tau index), the same clip-and-resolve sequence, and the same
    tie-break (first minimal SSE encountered in that order) to stay
    fixture-parity-identical.

    Returns
    -------
    {ke, arms: [{k, tau}] (tau ascending, clipped arms carry k=0),
     fit_quality_r2: 1 - SSE/SST (SST about the mean; SST==0 -> 1.0 if the
       fit is exact else 0.0),
     fitted: [{t, value, fitted}], sse}
    """
    if not isinstance(arms, int) or arms < 1 or arms > 3:
        raise ValueError("arms must be an int in 1..3 (SPEC sec.2.4 caps K at 3)")
    ts = [float(p["t"]) for p in series]
    ys = [float(p["value"]) for p in series]
    if len(series) < arms + 1:
        raise ValueError("series needs at least arms+1 points")
    for i in range(1, len(ts)):
        if ts[i] < ts[i - 1]:
            raise ValueError("series must be ordered by ascending t")

    grid = sorted(set(float(t) for t in (tau_grid if tau_grid is not None
                                         else default_tau_grid())))
    n = len(ys)
    ybar = _mean(ys)
    sst = sum((y - ybar) ** 2 for y in ys)

    best = None  # (sse, taus, coefs)
    for taus in _combinations(grid, arms):
        if any(taus[j + 1] - taus[j] <= 1e-12 for j in range(arms - 1)):
            continue
        cols = [[1.0] * n]
        for tau in taus:
            cols.append([math.exp(-t / tau) for t in ts])
        coefs = _fit_columns(cols, ys)
        if coefs is None:
            continue
        sse = 0.0
        for i in range(n):
            pred = coefs[0]
            for j, tau in enumerate(taus):
                pred += coefs[j + 1] * cols[j + 1][i]
            sse += (ys[i] - pred) ** 2
        if best is None or sse < best[0] - 1e-15 * max(1.0, best[0]):
            best = (sse, taus, coefs)
    if best is None:
        raise ValueError("no solvable tau combination for the given series/grid")

    sse, taus, coefs = best
    fitted = []
    for i in range(n):
        pred = coefs[0]
        for j, tau in enumerate(taus):
            pred += coefs[j + 1] * math.exp(-ts[i] / tau)
        fitted.append({"t": ts[i], "value": ys[i], "fitted": pred})

    if sst == 0.0:
        r2 = 1.0 if sse < 1e-30 else 0.0
    else:
        r2 = 1.0 - sse / sst

    return {
        "ke": coefs[0],
        "arms": [{"k": coefs[j + 1], "tau": taus[j]} for j in range(arms)],
        "fit_quality_r2": r2,
        "fitted": fitted,
        "sse": sse,
    }


# ---------------------------------------------------------------------------
# C4 -- snapback detector
# ---------------------------------------------------------------------------


def snapback_detect(series):
    """C4 snap-back detector with pre-registered-direction gate input.

    Contract
    --------
    series : [{"cycle", "predicted_delta", "realized_delta"}] in cycle order
        (the caller's ordering IS the consecutiveness order; cycles need not
        be contiguous integers). Deltas are in the recorded sign convention
        (see module docstring): realized +0.16 means dBc moved toward the null
        in the recorded frame. No polarity re-interpretation happens here.

    Rule
    ----
    Pre-registered direction for a cycle = sign(predicted_delta). A cycle is
    an INVERSION when sign(realized_delta) OPPOSES sign(predicted_delta):
      * realized_delta == 0 -> NEUTRAL, never opposed (a zero move carries no
        direction; replay gate treats it as no-evidence, not counter-evidence).
      * predicted_delta == 0 -> no pre-registered direction -> never opposed.
    Consecutive inversion cycles are grouped into RUNS (in series order; a
    neutral or agreeing cycle breaks a run).
    snapback = True iff any run has length >= 2 (SPEC sec.2.5: >=2 consecutive
    disagreeing cycles moving against the pre-registered direction).

    Returns
    -------
    {snapback: bool,
     inversion_runs: [[cycle, ...], ...] (each run's cycle values in order),
     run_lengths: [int, ...] (parallel to inversion_runs),
     verdict: "snapback" | "no_snapback",   # strings only, never auto-action
     gate_input: {"action": "halt_round" | "continue"},
     gate_noise_context: None}  # caller (C4 route) attaches scorer offset
        # here when grader-pass variance exceeds the effect being gated
        # (SPEC sec.2.7; replay F1: 5.77 dBc offset vs 0.64 effect size)

    Edge cases: empty series -> no_snapback/continue; single inversion cycle
    -> run length 1 -> no_snapback; all-neutral -> no_snapback.
    """
    runs = []
    current = []
    for point in series:
        cycle = point["cycle"]
        pred_sign = _sign(float(point["predicted_delta"]))
        real = float(point["realized_delta"])
        if real == 0.0 or pred_sign == 0:
            inversion = False
        else:
            inversion = _sign(real) != pred_sign
        if inversion:
            current.append(cycle)
        else:
            if current:
                runs.append(current)
                current = []
    if current:
        runs.append(current)

    run_lengths = [len(r) for r in runs]
    snapback = any(l >= 2 for l in run_lengths)
    return {
        "snapback": snapback,
        "inversion_runs": runs,
        "run_lengths": run_lengths,
        "verdict": "snapback" if snapback else "no_snapback",
        "gate_input": {"action": "halt_round" if snapback else "continue"},
        "gate_noise_context": None,
    }


# ---------------------------------------------------------------------------
# selftest
# ---------------------------------------------------------------------------

TOOL_DIR = __file__.rsplit("/", 1)[0] if "/" in __file__ else "."
FIXTURE_PATH = TOOL_DIR + "/fixtures/visco-fixtures.json"

HYSTERESIS_ANCHOR_SUM = 102.86     # recorded round-3 sum |predicted - realized|
HYSTERESIS_ANCHOR_MEAN = 10.29
ANCHOR_TOL = 0.05
FLOAT_TOL = 1e-9


def _approx_equal(a, b, tol, path="$"):
    """Recursive structural comparison with float tolerance. Returns None if
    equal, else a human-readable mismatch description."""
    if isinstance(b, bool) or isinstance(a, bool):
        if a is b or a == b:
            return None
        return "%s: bool %r != %r" % (path, a, b)
    if a is None or b is None:
        if a is None and b is None:
            return None
        return "%s: %r != %r" % (path, a, b)
    if isinstance(a, (int, float)) and isinstance(b, (int, float)):
        if abs(float(a) - float(b)) <= tol * (1.0 + abs(float(b))):
            return None
        return "%s: %r != %r (diff %g)" % (path, a, b, abs(float(a) - float(b)))
    if isinstance(a, str) and isinstance(b, str):
        return None if a == b else "%s: %r != %r" % (path, a, b)
    if isinstance(a, list) and isinstance(b, list):
        if len(a) != len(b):
            return "%s: list length %d != %d" % (path, len(a), len(b))
        for i, (x, y) in enumerate(zip(a, b)):
            err = _approx_equal(x, y, tol, "%s[%d]" % (path, i))
            if err:
                return err
        return None
    if isinstance(a, dict) and isinstance(b, dict):
        if set(a) != set(b):
            return "%s: keys %r != %r" % (path, sorted(map(str, a)),
                                          sorted(map(str, b)))
        for k in a:
            err = _approx_equal(a[k], b[k], tol, "%s.%s" % (path, k))
            if err:
                return err
        return None
    return "%s: type mismatch %r vs %r" % (path, type(a), type(b))


def _run_case(kind, case):
    """Run one fixture case through the matching instrument. Raises on error."""
    inp = case["input"]
    if kind == "persistence":
        return persistence_stats(inp["applied_cells"], inp["regraded_passes"],
                                 inp["base_dbc"], inp["loaded_dbc"],
                                 inp["regraded_dbcs"])
    if kind == "hysteresis":
        return hysteresis_rollup(inp["rows"])
    if kind == "prony":
        return prony_fit(inp["series"], inp.get("arms", 2), inp.get("tau_grid"))
    if kind == "snapback":
        return snapback_detect(inp["series"])
    raise ValueError("unknown fixture kind %r" % (kind,))


def selftest(verbose=True):
    """Run every fixture case + the hard replay anchors. Returns list of
    (name, ok, detail). Fixtures are the truth (frozen outputs of this very
    module), so any mismatch means the module changed or the port drifted."""
    checks = []

    def check(name, ok, detail=""):
        checks.append((name, bool(ok), detail))
        return ok

    with open(FIXTURE_PATH, "r") as f:
        fx = json.load(f)
    check("fixture_file_loads", fx.get("version") == 1,
          "version=%r" % (fx.get("version"),))

    for kind in ("persistence", "hysteresis", "prony", "snapback"):
        for case in fx.get(kind, []):
            name = "%s/%s" % (kind, case["name"])
            try:
                actual = _run_case(kind, case)
                err = _approx_equal(actual, case["expected"], FLOAT_TOL)
                check(name, err is None, err or "")
            except Exception as exc:  # noqa: BLE001 - report, don't crash
                check(name, False, "exception: %s" % (exc,))

    # ---- hard anchors (independent of the frozen expected values) ----
    hys_cases = {c["name"]: c for c in fx.get("hysteresis", [])}
    if "round3_recorded" in hys_cases:
        out = hysteresis_rollup(hys_cases["round3_recorded"]["input"]["rows"])
        check("anchor_hysteresis_sum_10286",
              abs(out["total_sum_abs"] - HYSTERESIS_ANCHOR_SUM) <= ANCHOR_TOL,
              "total_sum_abs=%.6f" % (out["total_sum_abs"],))
        check("anchor_hysteresis_mean_1029",
              abs(out["total_mean_per_cycle"] - HYSTERESIS_ANCHOR_MEAN) <= 0.01,
              "mean=%.6f" % (out["total_mean_per_cycle"],))
    sb_cases = {c["name"]: c for c in fx.get("snapback", [])}
    if "round3_recorded" in sb_cases:
        out = snapback_detect(sb_cases["round3_recorded"]["input"]["series"])
        check("anchor_snapback_runs",
              out["inversion_runs"] == [[4], [6, 7], [10]]
              and out["run_lengths"] == [1, 2, 1] and out["snapback"] is True,
              "runs=%r" % (out["inversion_runs"],))
    per_cases = {c["name"]: c for c in fx.get("persistence", [])}
    if "nine_flips_all_persist" in per_cases:
        out = persistence_stats(**{
            k: v for k, v in per_cases["nine_flips_all_persist"]["input"].items()
        })
        # persistence_stats signature order differs from fixture input keys
        check("anchor_persistence_9_of_9",
              out["persisted_count"] == 9 and out["applied_count"] == 9
              and out["persistence_fraction"] == 1.0,
              "persisted=%r/%r" % (out["persisted_count"], out["applied_count"]))
    pr_cases = {c["name"]: c for c in fx.get("prony", [])}
    if "synthetic_exact_2arm" in pr_cases:
        inp = pr_cases["synthetic_exact_2arm"]["input"]
        out = prony_fit(inp["series"], inp.get("arms", 2), inp.get("tau_grid"))
        taus = sorted(a["tau"] for a in out["arms"])
        check("anchor_prony_exact_recovery",
              out["fit_quality_r2"] >= 0.999999
              and abs(taus[0] - 1.0) < 1e-9 and abs(taus[1] - 8.0) < 1e-9
              and abs(out["sse"]) < 1e-18,
              "r2=%.9f taus=%r sse=%g" % (out["fit_quality_r2"], taus, out["sse"]))

    return checks


def _main():
    checks = selftest()
    n_pass = sum(1 for _, ok, _ in checks if ok)
    for name, ok, detail in checks:
        print(("PASS" if ok else "FAIL") + " " + name + ((": " + detail) if detail and not ok else ""))
    print("---")
    print("%d/%d checks passed" % (n_pass, len(checks)))
    return 0 if n_pass == len(checks) else 1


if __name__ == "__main__":
    raise SystemExit(_main())