#!/usr/bin/env node
// test-limits.mjs — limits/2: 4000-item caps, uncached-chunk budget, bulk KV reads, KV overflow storage.
import assert from "node:assert/strict";
import { ApiError } from "./lib/http.mjs";
import { validateDocs, embedDocuments, MAX_DOCS, MAX_UNCACHED_DOCS } from "./lib/embed-pipeline.mjs";
import { MAX_ITEMS, JSON_BODY_LIMIT, D1_MAP_JSON_LIMIT } from "./lib/limits.mjs";
import { saveStoredMap, loadStoredMapJson } from "./lib/map-store.mjs";
import { encodeMap } from "./lib/map-storage.mjs";
let pass=0, fail=0; const t=async(n,f)=>{try{await f();pass++;console.log("  ok  - "+n);}catch(e){fail++;console.log("FAIL  - "+n+"\n        "+(e?.stack||e));}};
const expectApi=async(f,status)=>{try{await f();}catch(e){assert.ok(e instanceof ApiError,String(e));assert.equal(e.status,status,e.message);return e;}throw new Error("expected ApiError("+status+")");};
await t("constants: 4000 items, 64 MiB body, 1.9 MB D1 inline", ()=>{assert.equal(MAX_ITEMS,4000);assert.equal(MAX_DOCS,4000);assert.equal(JSON_BODY_LIMIT,64*1024*1024);assert.equal(D1_MAP_JSON_LIMIT,1_900_000);});
await t("validateDocs accepts 504 docs and rejects 4001 with 413", ()=>{validateDocs(Array.from({length:504},(_,i)=>"doc "+i+" body text"));expectApi(()=>validateDocs(Array.from({length:4001},()=>"x")),413);});
function fakeVec(text){const v=new Array(768).fill(0);for(let i=0;i<text.length;i++)v[i%768]+=Math.sin(text.charCodeAt(i)*(i+1)*0.017);if(v.every(x=>x===0))v[0]=1;return v;}
function env({bulk=true}={}){const kv=new Map();const c={ai:0,gets:0,bulkGets:0,puts:0};return{AI:{async run(m,o){c.ai++;return{data:o.text.map(fakeVec)};}},SITE:{async get(k,type){if(Array.isArray(k)){if(!bulk)throw new TypeError("no bulk");c.bulkGets++;const r=new Map();for(const kk of k){const v=kv.get(kk);r.set(kk,v===undefined?null:JSON.parse(v));}return r;}c.gets++;const v=kv.get(k);return v===undefined?null:(type==="json"?JSON.parse(v):v);},async put(k,v){c.puts++;kv.set(k,v);},async delete(k){kv.delete(k);}},_c:c,_kv:kv};}
await t("bulk KV reads: 504 docs -> 6 bulk gets, 0 per-key gets; second call all cache hits, 0 AI calls", async()=>{const e=env();const docs=Array.from({length:504},(_,i)=>"Skill document "+i+" ".repeat(20)+"body");const r1=await embedDocuments(e,docs);assert.equal(r1.vectors.length,504);assert.equal(e._c.bulkGets,6);assert.equal(e._c.gets,0);assert.ok(e._c.ai>0);const ai=e._c.ai;const r2=await embedDocuments(e,docs);assert.equal(e._c.ai,ai);assert.equal(r2.metadata.cache_hits,504);});
await t("falls back to per-key gets when the KV binding has no bulk get", async()=>{const e=env({bulk:false});await embedDocuments(e,Array.from({length:12},(_,i)=>"d"+i+" text"));assert.equal(e._c.gets,12);});
await t("uncached budget: >1000 uncached docs -> 413 with warm-up hint and counts; no AI call", async()=>{const e=env();const docs=Array.from({length:1001},(_,i)=>"u"+i+" text");const err=await expectApi(()=>embedDocuments(e,docs),413);assert.match(err.message,/warm the content-hash embedding cache/);assert.equal(err.extra.uncached_docs,1001);assert.equal(e._c.ai,0);});
await t("warm-up path: after batching the same 1001 docs through embed in slices, the full request succeeds", async()=>{const e=env();const docs=Array.from({length:1001},(_,i)=>"w"+i+" text");for(let i=0;i<docs.length;i+=400)await embedDocuments(e,docs.slice(i,i+400));const ai=e._c.ai;const r=await embedDocuments(e,docs);assert.equal(r.metadata.cache_hits,1001);assert.equal(e._c.ai,ai);});
function fakeDb(){const rows=new Map();let next=1;const st={};return{rows,prepare(sql){return{bind(...a){return{async run(){if(sql.startsWith("INSERT")){const id=next++;rows.set(id,{map_json:a[13]});return{meta:{last_row_id:id}};}if(sql.startsWith("UPDATE")){rows.get(a[1]).map_json=a[0];return{};}if(sql.startsWith("DELETE")){rows.delete(a[0]);return{};}},async first(){if(sql.startsWith("SELECT map_json")){const r=rows.get(a[0]);return r?{map_json:r.map_json}:null;}return null;}};}};}};}
await t("small map stored inline in D1 and read back identically", async()=>{const db=fakeDb();const e=env();const map={frame_id:"f",names:["a","b"],pts_full:[[0,0,1],[0,1,0]],bits:[[0,1],[1,0]],null:{z:1.2,verdict:"v"},n:2,D:768,d:2,seed:1,V2:0.5};const id=await saveStoredMap(db,e,map,"vectors");assert.equal(id,1);assert.equal(JSON.parse(db.rows.get(1).map_json).frame_id,"f");const back=await loadStoredMapJson(db,e,1);assert.deepEqual(back,map);assert.equal(e._kv.size,0);});
await t("oversize map goes to KV overflow with a D1 pointer; read back identically; delete cleans up", async()=>{const db=fakeDb();const e=env();const big={frame_id:"big",names:Array.from({length:3000},(_,i)=>"item_"+i),pts_full:Array.from({length:3000},(_,i)=>[i*0.000123,i*0.000456,i*0.000789]),bits:Array.from({length:3000},(_,i)=>[i&1,(i>>1)&1,(i>>2)&1,(i>>3)&1,(i>>4)&1,(i>>5)&1,(i>>6)&1,(i>>7)&1,(i>>8)&1]),math_diagnostics:{per_input:Array.from({length:3000},(_,i)=>({index:i,name:"item_"+i,margins:Array.from({length:9},(_,j)=>({axis:j,signed_margin:0.123456789+i,distance_to_threshold:0.123456789,perturbation_bound:null,bit:1,status:"needs-roundoff-bound"}))}))},null:{z:0,verdict:"x"}};const bytes=new TextEncoder().encode(encodeMap(big,{limit:Infinity})).length;assert.ok(bytes>D1_MAP_JSON_LIMIT,"fixture must exceed inline limit: "+bytes);const id=await saveStoredMap(db,e,big,"vectors");const ptr=JSON.parse(db.rows.get(id).map_json);assert.equal(ptr.__kv,"map-json:"+id);assert.equal(ptr.bytes,bytes);assert.ok(e._kv.has("map-json:"+id));const back=await loadStoredMapJson(db,e,id);assert.equal(back.names.length,3000);assert.deepEqual(back.math_diagnostics.per_input[2999].margins[8],big.math_diagnostics.per_input[2999].margins[8]);assert.equal(await loadStoredMapJson(db,e,999),null);});
await t("oversize map with no KV binding is an explicit 413", async()=>{const db=fakeDb();const big={names:Array.from({length:300000},(_,i)=>"name_"+i)};await expectApi(()=>saveStoredMap(db,{},big,"x"),413);});
console.log(`\n${pass}/${pass+fail} passed`); if(fail)process.exit(1);
